### ISSUE TITLE
编译问题  

### ISSUE THREAD

**Issue by North9bay** [103style/android-database-sqlcipher#1]
我的Ubuntu是18以上的版本  其他的配置都是按照大佬你的博客上来的，当我android studio build项目时，会出现“Cause：error = 13  权限不够”这种问题，具体问题我看了一下，大概是调用task build openssl下面的“commandLine  ./build-openssl-librarise.sh”时出现的错误，大佬能不能加一下小弟的扣扣（792521565），指导一下

**Comment by 103style** [comment]
Android Studio  导入项目之后  不需要编译，只要把工程 所需要的sdk编译版本 安装好就行了。

你现在只要关掉Android Studio.
在android-database-sqlcipher目录 打开 命令窗口，执行以下命令就好
```
* make  init 
* make build-release
```

**Comment by North9bay** [comment]
大神，我在build-release的时候报，显示build.gradle line 1
![image](https://user-images.githubusercontent.com/30312418/57349965-b9eb2180-718e-11e9-8c5b-9de37d289850.png)

**Comment by North9bay** [comment]
还有我这边用的不是openjdk 我用的是Oracle jdk1.8   不知道这个有没有影响

**Comment by 103style** [comment]
你可以用下面的代码 换成 openjdk 1.8.0 试试
```
1.按Ctrl + Alt + T打开终端。打开后，运行下面的命令来添加PPA：
sudo add-apt-repository ppa:openjdk-r/ppa
2.之后，更新系统包缓存并安装OpenJDK 8： 
sudo apt-get update
sudo apt-get install openjdk-8-jdk
3.如果您的系统上安装了多个Java版本。运行下面的命令设置默认的Java：
sudo update-alternatives --config java
键入一个数字以选择Java版本。
设置默认的java版本
并通过运行以下命令设置默认Java编译器：
sudo update-alternatives --config javac 
4.最后通过运行以下步骤查看当前的Java版本：
java -version
它输出这样的东西：
openjdk版本“1.8.0_01-internal”
```

然后再次执行
```
* make  init 
* make clean
* make build-release
```

**Comment by North9bay** [comment]
大神   
我尝试了   结果还是报上面那个错  不知道是不是还有什么细节没注意到

**Comment by 103style** [comment]
请确认编译环境配置：
检查 NDK  是否是  r15c 版本， 不是的话，下载r15c

如果还有问题的话   建议试试 ubuntu 16.04版本

这个报错我在编译的过程中也没遇到过...
